version: '3.5'
services:

  plex-media-server:
    image: plexinc/pms-docker
    extends:
      file: hardware-acceleration.yaml
      service: hardware-acceleration
    env_file: environment.d/plex.env
    environment:
      PLEX_UID: ${HOST_USER_ID:?HOST_USER_ID is required}
      PLEX_GID: ${HOST_GROUP_ID:?HOST_GROUP_ID is required}
    network_mode: host
    shm_size: ${SHM_SIZE:-64MB}
    volumes:
      - ${CONFIG_PATH:-plex-config}:/config
      - ${TRANSCODE_PATH:-plex-transcode}:/transcode
      - ${MEDIA_PATH:?MEDIA_PATH is required}:/data:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  plex-config: {}
  plex-transcode: {}
